input {
    file {
        path => "/data-logs/*.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        tags => ["${SOURCE_TAG}"]
        type => "${SOURCE_TYPE}"
    }
}

filter{
    grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
}

output {
    elasticsearch {
        hosts => [ "http://elasticsearch:9200" ]
        index => "${SOURCE_INDEX}_%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
}