input {
    file {
	codec => json
        path => "${SONAR_LOGS_PATH}"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        tags => ["SQ", "SonarQube"]
        type => "SonarQube"
    }
}

filter{
}

output {
    elasticsearch {
        hosts => [ "${ES_HOST}" ],
        index => "dso_sq_%{+YYYY.MM.dd}"
    }
}