input {
    file {
	codec => json
        path => "/sonar-logs/*.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        tags => ["SQ", "SonarQube"]
        type => "SonarQube"
    }
}

filter{
    grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
}

output {
    elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "dso_sq_%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
}